/**
 * Created by ajbrown on 1/23/14.
 */

seed = {

    // Dog Breed Suggestions
    // list obtained from AKC website: http://www.akc.org/breeds/complete_breed_list.cfm
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Affenpinscher')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Afghan Hound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Airedale Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Akita')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Alaskan Malamute')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'American English Coonhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'American Eskimo Dog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'American Foxhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'American Staffordshire Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'American Water Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Anatolian Shepherd Dog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Australian Cattle Dog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Australian Shepherd')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Australian Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Basenji')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Basset Hound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Beagle')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Bearded Collie')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Beauceron')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Bedlington Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Belgian Malinois')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Belgian Sheepdog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Belgian Tervuren')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Bernese Mountain Dog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Bichon Frise')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Black Russian Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Black and Tan Coonhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Bloodhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Bluetick Coonhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Border Collie')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Border Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Borzoi')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Boston Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Bouvier des Flandres')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Boxer')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Boykin Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Briard')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Brittany')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Brussels Griffon')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Bull Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Bulldog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Bullmastiff')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Cairn Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Canaan Dog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Cane Corso')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Cardigan Welsh Corgi')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Cavalier King Charles Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Cesky Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Chesapeake Bay Retriever')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Chihuahua')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Chinese Crested')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Chinese Shar-Pei')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Chinook')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Chow Chow')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Clumber Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Cocker Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Collie')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Curly-Coated Retriever')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Dachshund')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Dalmatian')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Dandie Dinmont Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Doberman Pinscher')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Dogue de Bordeaux')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'English Cocker Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'English Foxhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'English Setter')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'English Springer Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'English Toy Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Entlebucher Mountain Dog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Field Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Finnish Lapphund')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Finnish Spitz')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Flat-Coated Retriever')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'French Bulldog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'German Pinscher')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'German Shepherd Dog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'German Shorthaired Pointer')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'German Wirehaired Pointer')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Giant Schnauzer')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Glen of Imaal Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Golden Retriever')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Gordon Setter')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Great Dane')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Great Pyrenees')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Greater Swiss Mountain Dog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Greyhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Harrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Havanese')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Ibizan Hound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Icelandic Sheepdog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Irish Red and White Setter')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Irish Setter')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Irish Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Irish Water Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Irish Wolfhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Italian Greyhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Japanese Chin')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Keeshond')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Kerry Blue Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Komondor')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Kuvasz')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Labrador Retriever')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Lakeland Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Leonberger')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Lhasa Apso')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Lowchen')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Maltese')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Manchester Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Mastiff')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Miniature Bull Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Miniature Pinscher')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Miniature Schnauzer')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Neapolitan Mastiff')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Newfoundland')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Norfolk Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Norwegian Buhund')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Norwegian Elkhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Norwegian Lundehund')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Norwich Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Nova Scotia Duck Tolling Retriever')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Old English Sheepdog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Otterhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Papillon')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Parson Russell Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Pekingese')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Pembroke Welsh Corgi')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Petit Basset Griffon Vendeen')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Pharaoh Hound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Plott')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Pointer')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Polish Lowland Sheepdog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Pomeranian')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Poodle')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Portuguese Podengo Pequeno')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Portuguese Water Dog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Pug')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Puli')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Pyrenean Shepherd')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Redbone Coonhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Rhodesian Ridgeback')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Rottweiler')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Russell Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Saluki')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Samoyed')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Schipperke')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Scottish Deerhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Scottish Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Sealyham Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Shetland Sheepdog')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Shiba Inu')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Shih Tzu')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Siberian Husky')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Silky Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Skye Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Smooth Fox Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Soft Coated Wheaten Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Spinone Italiano')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'St. Bernard')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Staffordshire Bull Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Standard Schnauzer')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Sussex Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Swedish Vallhund')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Tibetan Mastiff')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Tibetan Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Tibetan Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Toy Fox Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Treeing Walker Coonhound')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Vizsla')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Weimaraner')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Welsh Springer Spaniel')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Welsh Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'West Highland White Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Whippet')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Wire Fox Terrier')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Wirehaired Pointing Griffon')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Xoloitzcuintli')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'DOG', name: 'Yorkshire Terrier')


    // Cat Breed Suggestions
    // list obtained from catster: http://www.catster.com/cat-breeds/
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Abyssinian')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'American Bobtail')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'American Curl')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'American Ringtail')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'American Shorthair')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'American Wirehair')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Anatolian')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Australian Mist')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Balinese')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Bengal')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Birman')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Bombay')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'British Shorthair')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Burmese')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Burmilla')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'California Spangled Cat')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Chantilly/Tiffany')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Chartreux')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Chausie')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Colorpoint Shorthair')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Cornish Rex')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Devonshire Rex')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Domestic Long Hair')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Domestic Medium Hair')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Domestic Shorthair')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Don Hairless')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Egyptian Mau')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'European Burmese')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'European Shorthair')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Exotic Shorthair')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Gato')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Havana Brown')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Highlander')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Himalayan')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Japanese Bobtail')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Javanese')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Khao Manee')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Korat')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'LaPerm')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Maine Coon')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Manx')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Minskin')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Munchkin')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Nebelung')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Norwegian Forest Cat')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Ocicat')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Oriental')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Persian')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Peterbald')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Pixie-Bob')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Ragamuffin')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Ragdoll')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Russian Blue')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Savannah')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Scottish Fold')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Selkirk Rex')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Siamese')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Siberian')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Singapura')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Snowshoe')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Sokoke')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Somali')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Sphynx')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Thai')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Tiffanie')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Tonkinese')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Toyger')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Turkish Angora')
    breedSuggestion( meta: [ key: 'name', update: false ], species: 'CAT', name: 'Turkish Van')

    //Male name suggestions
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Bailey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Bandit')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Baxter')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Bear')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Beau')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Bentley')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Boomer')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Bruno')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Buddy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Buster')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Casey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Charlie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Cody')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Cooper')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Dakota')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Duke')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Gizmo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Gus')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Harley')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Henry')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Hunter')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Jack')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Jackson')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Jake')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Joey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Louie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Lucky')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Luke')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Max')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Maximus')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Milo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Murphy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Oliver')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Oscar')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Riley')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Rocco')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Rocky')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Romeo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Rudy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Rusty')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Sam')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Sammy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Samson')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Shadow')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Sparky')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Teddy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Toby')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Tucker')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Winston')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'ZeusAlex')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Angel')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Baby')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Blackie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Blue')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Bob')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Boo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Bubba')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Calvin')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Casper')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Chester')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Clyde')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Coco')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Cosmo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Dusty')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Elvis')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Felix')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Fluffy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Frankie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Fred')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Gabriel')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'George')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Harry')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Jasper')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Junior')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Kitty')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Leo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Loki')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Merlin')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Mickey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Midnight')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Mikey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Oreo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Peanut')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Pepper')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Prince')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Pumpkin')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Rascal')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Scooter')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Sebastian')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Simba')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Simon')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Smokey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Snowball')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Sonny')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Spencer')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Spike')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Sunny')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Sylvester')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Taz')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Thomas')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Tiger')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Tigger')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Tom')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Tommy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Willie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Yoda')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'male', name: 'Ziggy')

    //Female name suggestions.
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Abby')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Angel')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Annie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Bailey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Bella')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Belle')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Brandy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Casey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Chloe')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Coco')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Daisy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Dakota')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Dixie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Emma')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Ginger')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Gracie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Heidi')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Holly')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Honey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Jasmine')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Katie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Lady')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Lexi')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Lilly')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Lily')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Lola')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Lucy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Lulu')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Luna')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Madison')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Maggie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Mia')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Missy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Molly')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Penny')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Pepper')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Princess')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Rosie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Roxie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Roxy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Ruby')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Sadie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Samantha')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Sandy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Sasha')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Shelby')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Sophie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Stella')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Zoe')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Zoey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Allie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Amber')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Ashley')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Baby')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Bonnie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Boo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Buffy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Cali')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Callie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Cassie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Cleo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Cleopatra')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Cookie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Ella')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Emily')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Fiona')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Fluffy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Gizmo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Grace')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Isabella')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Isis')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Jade')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Kiki')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Kitty')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Lucky')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Maya')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Midnight')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Mimi')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Minnie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Miss')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Misty')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Mittens')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Mocha')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Muffin')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Nala')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Olivia')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Oreo')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Patches')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Peaches')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Peanut')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Phoebe')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Precious')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Pumpkin')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Sabrina')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Sassy')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Shadow')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Sheba')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Smokey')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Sophia')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Stalla')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Sugar')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Tabitha')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Tasha')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Tiger')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Tigger')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Tinkerbell')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Trixie')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Willow')
    nameSuggestion( meta: [ key: 'name', update: false ], sex: 'female', name: 'Xena')
}